package com.gildedgames.the_aether.client.models.entities;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

@SideOnly(Side.CLIENT)
public class IrkModel extends ModelBase {
   private final ModelRenderer headMain;
   private final ModelRenderer headFront;
   private final ModelRenderer eyes;
   private final ModelRenderer antR;
   private final ModelRenderer antL;
   private final ModelRenderer mandible;
   private final ModelRenderer thx;
   private final ModelRenderer legBase1;
   private final ModelRenderer legBase2;
   private final ModelRenderer legBase3;
   private final ModelRenderer abMain;
   private final ModelRenderer abSide;
   private final ModelRenderer abBack;
   private final ModelRenderer rFLeg1;
   private final ModelRenderer rFLeg2;
   private final ModelRenderer rFLeg3;
   private final ModelRenderer rFLegClaw;
   private final ModelRenderer rBLeg1;
   private final ModelRenderer rBLeg2;
   private final ModelRenderer rBLeg3;
   private final ModelRenderer rBLegClaw;
   private final ModelRenderer lBLeg1;
   private final ModelRenderer lBLeg2;
   private final ModelRenderer lBLeg3;
   private final ModelRenderer lBLegClaw;
   private final ModelRenderer lFLeg1;
   private final ModelRenderer lFLeg2;
   private final ModelRenderer lFLeg3;
   private final ModelRenderer lFLegClaw;
   private final ModelRenderer rMLeg2;
   private final ModelRenderer rMLeg1;
   private final ModelRenderer rMLeg3;
   private final ModelRenderer rMLegClaw;
   private final ModelRenderer lMLeg1;
   private final ModelRenderer lMLeg2;
   private final ModelRenderer lMLeg3;
   private final ModelRenderer lMLegClaw;

   public IrkModel() {
      this.textureWidth = 64;
      this.textureHeight = 128;
      this.headMain = new ModelRenderer(this, 15, 0);
      this.headMain.addBox(-2.0F, -1.5F, -4.0F, 4, 4, 4);
      this.headMain.setRotationPoint(0.0F, 19.0F, -10.0F);
      this.setRotation(this.headMain, 0.0872665F, 0.0F, 0.0F);
      this.headFront = new ModelRenderer(this, 39, 0);
      this.headFront.addBox(-1.5F, -1.0F, -6.0F, 3, 3, 2);
      this.setRotation(this.headFront, 0.0F, 0.0F, 0.0F);
      this.eyes = new ModelRenderer(this, 0, 0);
      this.eyes.addBox(-2.5F, -1.0F, -3.0F, 5, 2, 2);
      this.setRotation(this.eyes, 0.0F, 0.0F, 0.0F);
      this.antR = new ModelRenderer(this, 46, 28);
      this.antR.addBox(-10.0F, 0.5F, -2.5F, 7, 1, 1);
      this.setRotation(this.antR, -0.0872665F, -0.8235988F, 0.0F);
      this.antL = new ModelRenderer(this, 0, 28);
      this.antL.addBox(3.0F, 0.5F, -2.5F, 7, 1, 1);
      this.setRotation(this.antL, -0.0872665F, 0.8235988F, 0.0F);
      this.mandible = new ModelRenderer(this, 52, 0);
      this.mandible.addBox(-1.0F, 0.0F, -7.0F, 2, 2, 1);
      this.setRotation(this.mandible, 0.0F, 0.0F, 0.0F);
      this.thx = new ModelRenderer(this, 11, 9);
      this.thx.addBox(-4.0F, -3.0F, -1.0F, 8, 6, 12);
      this.thx.setRotationPoint(0.0F, 19.5F, -9.0F);
      this.setRotation(this.thx, 0.0F, 0.0F, 0.0F);
      this.legBase1 = new ModelRenderer(this, 17, 28);
      this.legBase1.addBox(-5.0F, -2.0F, 0.0F, 10, 4, 4);
      this.legBase1.setRotationPoint(0.0F, 19.5F, -9.0F);
      this.setRotation(this.legBase1, 0.0F, 0.0F, 0.0F);
      this.legBase2 = new ModelRenderer(this, 16, 37);
      this.legBase2.addBox(-5.5F, -2.0F, 5.0F, 11, 4, 4);
      this.legBase2.setRotationPoint(0.0F, 19.5F, -9.0F);
      this.setRotation(this.legBase2, 0.0F, 0.0F, 0.0F);
      this.legBase3 = new ModelRenderer(this, 15, 46);
      this.legBase3.addBox(-6.0F, -2.0F, 10.0F, 12, 4, 4);
      this.legBase3.setRotationPoint(0.0F, 19.5F, -9.0F);
      this.setRotation(this.legBase3, 0.0F, 0.0F, 0.0F);
      this.abMain = new ModelRenderer(this, 6, 55);
      this.abMain.addBox(-4.5F, -4.5F, 4.0F, 9, 7, 16);
      this.abMain.setRotationPoint(0.0F, 20.0F, -2.0F);
      this.setRotation(this.abMain, -0.0872665F, 0.0F, 0.0F);
      this.abSide = new ModelRenderer(this, 5, 79);
      this.abSide.addBox(-7.0F, -2.0F, 9.0F, 14, 4, 12);
      this.abSide.setRotationPoint(0.0F, 19.0F, -4.0F);
      this.setRotation(this.abSide, -0.0872665F, 0.0F, 0.0F);
      this.abBack = new ModelRenderer(this, 23, 96);
      this.abBack.addBox(-3.0F, -2.0F, 13.0F, 6, 4, 2);
      this.abBack.setRotationPoint(0.0F, 20.0F, 5.0F);
      this.setRotation(this.abBack, -0.0872665F, 0.0F, 0.0F);
      this.rFLeg1 = new ModelRenderer(this, 25, 103);
      this.rFLeg1.addBox(-1.033333F, -3.0F, -1.0F, 2, 4, 2);
      this.rFLeg1.setRotationPoint(-5.0F, 20.0F, -7.0F);
      this.setRotation(this.rFLeg1, 0.0F, 2.617994F, -0.8726646F);
      this.rFLeg2 = new ModelRenderer(this, 25, 110);
      this.rFLeg2.addBox(1.0F, -3.0F, -1.5F, 6, 2, 3);
      this.setRotation(this.rFLeg2, 0.0F, 0.0F, -0.8726646F);
      this.rFLeg3 = new ModelRenderer(this, 25, 116);
      this.rFLeg3.addBox(2.0F, -7.5F, -1.0F, 6, 2, 2);
      this.setRotation(this.rFLeg3, 0.0F, 0.0F, 0.0F);
      this.rFLegClaw = new ModelRenderer(this, 25, 122);
      this.rFLegClaw.addBox(8.0F, -7.5F, -0.5F, 3, 1, 1);
      this.setRotation(this.rFLegClaw, 0.0F, 0.0F, 0.0F);
      this.rBLeg1 = new ModelRenderer(this, 25, 103);
      this.rBLeg1.addBox(-1.033333F, -3.0F, -1.0F, 2, 4, 2);
      this.rBLeg1.setRotationPoint(-6.5F, 20.0F, 3.0F);
      this.setRotation(this.rBLeg1, 0.0F, -2.617994F, -0.8726646F);
      this.rBLeg2 = new ModelRenderer(this, 25, 110);
      this.rBLeg2.addBox(1.0F, -3.0F, -1.5F, 6, 2, 3);
      this.setRotation(this.rBLeg2, 0.0F, 0.0F, -0.8726646F);
      this.rBLeg3 = new ModelRenderer(this, 25, 116);
      this.rBLeg3.addBox(2.0F, -7.5F, -1.0F, 6, 2, 2);
      this.setRotation(this.rBLeg3, 0.0F, 0.0F, 0.0F);
      this.rBLegClaw = new ModelRenderer(this, 25, 122);
      this.rBLegClaw.addBox(8.0F, -7.5F, -0.5F, 3, 1, 1);
      this.setRotation(this.rBLegClaw, 0.0F, 0.0F, 0.0F);
      this.lBLeg1 = new ModelRenderer(this, 25, 103);
      this.lBLeg1.addBox(-1.033333F, -3.0F, -1.0F, 2, 4, 2);
      this.lBLeg1.setRotationPoint(6.5F, 20.0F, 3.0F);
      this.setRotation(this.lBLeg1, 0.0F, -0.5235988F, 0.8726646F);
      this.lBLeg2 = new ModelRenderer(this, 25, 110);
      this.lBLeg2.addBox(1.0F, -3.0F, -1.5F, 6, 2, 3);
      this.setRotation(this.lBLeg2, 0.0F, 0.0F, -0.8726646F);
      this.lBLeg3 = new ModelRenderer(this, 25, 116);
      this.lBLeg3.addBox(2.0F, -7.5F, -1.0F, 6, 2, 2);
      this.setRotation(this.lBLeg3, 0.0F, 0.0F, 0.0F);
      this.lBLegClaw = new ModelRenderer(this, 25, 122);
      this.lBLegClaw.addBox(8.0F, -7.5F, -0.5F, 3, 1, 1);
      this.setRotation(this.lBLegClaw, 0.0F, 0.0F, 0.0F);
      this.lFLeg1 = new ModelRenderer(this, 25, 103);
      this.lFLeg1.addBox(-1.0F, -3.0F, -1.0F, 2, 4, 2);
      this.lFLeg1.setRotationPoint(5.0F, 20.0F, -7.0F);
      this.setRotation(this.lFLeg1, 0.0F, 0.5235988F, 0.8726646F);
      this.lFLeg2 = new ModelRenderer(this, 25, 110);
      this.lFLeg2.addBox(1.0F, -3.0F, -1.5F, 6, 2, 3);
      this.setRotation(this.lFLeg2, 0.0F, 0.0F, -0.8726646F);
      this.lFLeg3 = new ModelRenderer(this, 25, 116);
      this.lFLeg3.addBox(2.0F, -7.5F, -1.0F, 6, 2, 2);
      this.setRotation(this.lFLeg3, 0.0F, 0.0F, 0.0F);
      this.lFLegClaw = new ModelRenderer(this, 25, 122);
      this.lFLegClaw.addBox(8.0F, -7.5F, -0.5F, 3, 1, 1);
      this.setRotation(this.lFLegClaw, 0.0F, 0.0F, 0.0F);
      this.rMLeg1 = new ModelRenderer(this, 25, 103);
      this.rMLeg1.addBox(-1.033333F, -3.0F, -1.0F, 2, 4, 2);
      this.rMLeg1.setRotationPoint(-6.0F, 20.0F, -2.0F);
      this.setRotation(this.rMLeg1, 0.0F, 3.141593F, -0.8726646F);
      this.rMLeg2 = new ModelRenderer(this, 25, 110);
      this.rMLeg2.addBox(1.0F, -3.0F, -1.5F, 6, 2, 3);
      this.setRotation(this.rMLeg2, 0.0F, 0.0F, -0.8726646F);
      this.rMLeg3 = new ModelRenderer(this, 25, 116);
      this.rMLeg3.addBox(2.0F, -7.5F, -1.0F, 6, 2, 2);
      this.setRotation(this.rMLeg3, 0.0F, 0.0F, 0.0F);
      this.rMLegClaw = new ModelRenderer(this, 25, 122);
      this.rMLegClaw.addBox(8.0F, -7.5F, -0.5F, 3, 1, 1);
      this.setRotation(this.rMLegClaw, 0.0F, 0.0F, 0.0F);
      this.lMLeg1 = new ModelRenderer(this, 25, 103);
      this.lMLeg1.addBox(-1.0F, -3.0F, -1.0F, 2, 4, 2);
      this.lMLeg1.setRotationPoint(6.0F, 20.0F, -2.0F);
      this.setRotation(this.lMLeg1, 0.0F, 0.0F, 0.8726646F);
      this.lMLeg2 = new ModelRenderer(this, 25, 110);
      this.lMLeg2.addBox(1.0F, -3.0F, -1.5F, 6, 2, 3);
      this.setRotation(this.lMLeg2, 0.0F, 0.0F, -0.8726646F);
      this.lMLeg3 = new ModelRenderer(this, 25, 116);
      this.lMLeg3.addBox(2.0F, -7.5F, -1.0F, 6, 2, 2);
      this.setRotation(this.lMLeg3, 0.0F, 0.0F, 0.0F);
      this.lMLegClaw = new ModelRenderer(this, 25, 122);
      this.lMLegClaw.addBox(8.0F, -7.5F, -0.5F, 3, 1, 1);
      this.setRotation(this.lMLegClaw, 0.0F, 0.0F, 0.0F);
      this.rFLeg1.addChild(this.rFLeg2);
      this.rFLeg1.addChild(this.rFLeg3);
      this.rFLeg1.addChild(this.rFLegClaw);
      this.rMLeg1.addChild(this.rMLeg2);
      this.rMLeg1.addChild(this.rMLeg3);
      this.rMLeg1.addChild(this.rMLegClaw);
      this.rBLeg1.addChild(this.rBLeg2);
      this.rBLeg1.addChild(this.rBLeg3);
      this.rBLeg1.addChild(this.rBLegClaw);
      this.lFLeg1.addChild(this.lFLeg2);
      this.lFLeg1.addChild(this.lFLeg3);
      this.lFLeg1.addChild(this.lFLegClaw);
      this.lMLeg1.addChild(this.lMLeg2);
      this.lMLeg1.addChild(this.lMLeg3);
      this.lMLeg1.addChild(this.lMLegClaw);
      this.lBLeg1.addChild(this.lBLeg2);
      this.lBLeg1.addChild(this.lBLeg3);
      this.lBLeg1.addChild(this.lBLegClaw);
      this.headMain.addChild(this.headFront);
      this.headMain.addChild(this.eyes);
      this.headMain.addChild(this.antR);
      this.headMain.addChild(this.antL);
   }

   public void render(Entity entity, float limbSwing, float limbSwingAngle, float entityTickTime, float rotationYaw, float rotationPitch, float unitPixel) {
      super.render(entity, limbSwing, limbSwingAngle, entityTickTime, rotationYaw, rotationPitch, unitPixel);
      this.setRotationAngles(limbSwing, limbSwingAngle, entityTickTime, rotationYaw, rotationPitch, unitPixel, entity);
      this.headMain.render(unitPixel);
      this.thx.render(unitPixel);
      this.legBase1.render(unitPixel);
      this.legBase2.render(unitPixel);
      this.legBase3.render(unitPixel);
      this.abMain.render(unitPixel);
      this.abSide.render(unitPixel);
      this.abBack.render(unitPixel);
      this.rFLeg1.render(unitPixel);
      this.rMLeg1.render(unitPixel);
      this.rBLeg1.render(unitPixel);
      this.lFLeg1.render(unitPixel);
      this.lMLeg1.render(unitPixel);
      this.lBLeg1.render(unitPixel);
   }

   private void setRotation(ModelRenderer model, float x, float y, float z) {
      model.rotateAngleX = x;
      model.rotateAngleY = y;
      model.rotateAngleZ = z;
   }

   public void setRotationAngles(float limbSwing, float limbSwingAngle, float entityTickTime, float rotationYaw, float rotationPitch, float unitPixel, Entity entity) {
      super.setRotationAngles(limbSwing, limbSwingAngle, entityTickTime, rotationYaw, rotationPitch, unitPixel, entity);
      float correction = 0.8726646F;
      float legMovement = MathHelper.cos(limbSwing * 2.5F) * 0.9F * limbSwingAngle;
      //this.headMain.rotateAngleY = MathUtil.toRad(rotationYaw);
      this.rFLeg1.rotateAngleX = legMovement - correction;
      this.rMLeg1.rotateAngleX = -legMovement;
      this.rBLeg1.rotateAngleX = legMovement + correction;
      this.lFLeg1.rotateAngleX = legMovement + correction;
      this.lMLeg1.rotateAngleX = -legMovement;
      this.lBLeg1.rotateAngleX = legMovement - correction;
   }
}
